### ISSUE TITLE
Season is sometimes NA

### ISSUE THREAD

**Issue by walinchus** [danmorse314/hockeyR#2]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/25959269/134414900-4d2d97f5-b373-436c-832c-b4065c7f08a7.png">

`df <- get_jersey_players(21)` gives you one season with an NA. I'm not sure if this affects other numbers, but just FYI.

**Comment by danmorse314** [comment]
Hmmm looks like something weird in the hockey-ref tables, I might have to go fix that line manually. I'll try and get a fix for that tonight, let me know if it turns up anywhere else that you notice!
![image](https://user-images.githubusercontent.com/44938476/134431105-ec2106bb-2206-4b6e-bf9c-6b8a640b92e4.png)
