### ISSUE TITLE
PBP sometimes read "12 num_on" for shift changes

### ISSUE THREAD

**Issue by Colinifer** [danmorse314/hockeyR#3]
I've attached a csv complete with `game_id`, and `event_idx` columns to compare.

Most of the time it looks like the issue happens at the start of a game or at the start of a period, with a few exceptions.

Is the data supposed to read this way?

[12_players_on.csv](https://github.com/danmorse314/hockeyR/files/7794714/12_players_on.csv)

**Comment by danmorse314** [comment]
This has been fixed now. There were instances of shifts that lasted 0 seconds -- ie players going onto the ice but immediately going back off, probably to do with the home team last change. The `get_game_shifts` function now removes those shifts, will rescrape the data and upload to the repo
