### ISSUE TITLE
missing goaltender data

### ISSUE THREAD

**Issue by topepo** [danmorse314/hockeyR#5]
There are some results where the data (probably?) should have non-missing data for one of the goaltenders. 

Here's an example where all of PIT's goalie data are missing for the shot/missed/goal events. 

``` r
library(hockeyR)
library(tidyverse)
library(tidylog, warn.conflicts = FALSE)

check_2015 <- 
  load_pbp('2015-16') %>%
  filter( event %in% c("Shot", "Missed Shot", "Goal") ) %>% 
  filter( (is.na(home_goalie) | is.na(away_goalie)) & !isTRUE(empty_net) )
#> filter: removed 741,256 rows (87%), 110,264 rows remaining
#> filter: removed 100,914 rows (92%), 9,350 rows remaining

# Some missing data in goaltender field. This appears to be an
# error in the data. For example, game 2015020010 has PIT goalie missing but
# Janmark scored on Fleury at 1:39 into the first period (event_idx = 19). See
# https://www.nhl.com/news/smith-coyotes-hang-on-to-defeat-penguins/c-174477

check_2015 %>% 
  filter(game_id == "2015020010") %>% 
  filter(event == "Goal") %>% 
  select(event_idx, home_goalie, away_goalie, event_team_type, event_team_abbr, empty_net)
#> filter: removed 9,257 rows (99%), 93 rows remaining
#> filter: removed 90 rows (97%), 3 rows remaining
#> select: dropped 101 variables (event_type, event, secondary_type, event_team, description, …)
#> # A tibble: 3 × 6
#>   event_idx home_goalie away_goalie event_team_type event_team_abbr empty_net
#>       <dbl> <chr>       <chr>       <chr>           <chr>           <lgl>    
#> 1        19 Antti.Niemi <NA>        home            DAL             FALSE    
#> 2       301 Antti.Niemi <NA>        home            DAL             FALSE    
#> 3       627 Antti.Niemi <NA>        home            DAL             FALSE
```

<sup>Created on 2022-08-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by danmorse314** [comment]
Did some digging and it looks like the dash in Marc-Andre Fleury didn't parse correctly during scraping. I found a way to fix it but will have to go through and scrape it again before it gets fully updated.

As for the rest of the plays, I think I have an answer. First off the `!isTRUE(empty_net)` filter doesn't remove shots on an empty net when I try it on my machine. If I change it to `empty_net != TRUE` it leaves fewer rows remaining

`df <- pbp_2016 |>`
`   filter(event_type %in% c("SHOT","MISSED_SHOT","GOAL")) |>`
`   filter((is.na(home_goalie) | is.na(away_goalie)) & empty_net != TRUE)`
`#>filter: removed 741,256 rows (87%), 110,264 rows remaining`
`#>filter: removed 109,742 rows (>99%), 522 rows remaining`

From what I can tell the plays left where the goalie is `NA` happened during a delayed penalty -- there's a variable `extra_attacker` that shows the shooting team had their goalie pulled.

**Comment by danmorse314** [comment]
Marc-Andre Fleury's name has been fixed and all the pbp has been rescraped
