### ISSUE TITLE
Missing pbp data mid-way through game for some 2022-23 games

### ISSUE THREAD

**Issue by mrbilltran** [danmorse314/hockeyR#8]
For pbp events using scrape_game, towards the end of a game at some point the data is not filled out:
- strength_state defaults to 0v0
- num_on, players_on, num_off, players_off, home_on_#, away_on_# are all NA.

This issue was seen in the following 2022-23 games so far:

2022020008
2022020009
2022020010

**Comment by danmorse314** [comment]
That will happen with events at the very beginning and very end of the game. Ex: "Game Scheduled" is an event in the play-by-play data but there are no skaters on the ice at the time. Looks like this year the only events with an invalid strength state are game starts and ends, you should be able to just filter out those strength states or events before doing any analyses.

`> pbp <- hockeyR::load_pbp()
> ovo <- dplyr::filter(pbp, strength_state %in% c("0v0","0v5","5v0"))
> unique(ovo$event)
[1] "Game Scheduled" "Period End"     "Game End" `

**Comment by mrbilltran** [comment]
Yes, for those non-in-game events, 0v0 makes perfect sense!

It just so happened that last night, every single third period event for the listed games above had strength_state = 0v0. Checking it now, they are properly filled in. I wonder if it might have do with a delay in updating from the NHL side!

I can check again with today's games to see if the delay is consistent.

**Comment by danmorse314** [comment]
Oh yeah there is a bit of a delay for the shift reports to come through fully, I bet they just weren't ready yet at the time you were scraping! Good call
